export const projects = [
  {
    title: "RecruitIt",
    completed: false,
    deployed: false,
    description:
      "RecruitIt modernizes employee administration by bringing workforce management and document issuance into a single platform. From maintaining employee records to generating official documents, the application emphasizes automation, security, and an intuitive user experience powered by a scalable full-stack architecture.",
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "JWT",
      "Google OAuth",
      "Redis",
      "BullMQ",
      "Nodemailer",
      "Cloudinary",
      "Multer",
      "Zod",
      "TanStack Query",
      "Axios",
    ],
    coverImg: "/hero-image.jpg",
  },
  {
    title: "RideMate",
    completed: true,
    deployed: true,
    description:
      "RideMate is a full-stack carpooling platform that connects drivers and passengers through intelligent ride matching while prioritizing safety and user privacy. It features real-time chat, live location sharing, document-based user verification, admin moderation, ride notifications, and a scalable backend architecture designed for reliable, real-world transportation workflows.",
    techStack: [
      "React",
      "Tailwind CSS",
      "DaisyUI",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "Socket.IO",
      "JWT",
      "Cloudinary",
      "Multer",
      "Leaflet",
      "OpenStreetMap",
      "Nodemailer",
      "Axios",
      "Context API",
    ],
    coverImg: "/hero-image.jpg",
  },
  {
    title: "StudoSphere",
    completed: true,
    deployed: true,
    description:
      "StudoSphere is a comprehensive campus management platform that bridges communication between students and placement coordinators. It combines AI-powered discussions, collaborative productivity tools, faculty discovery, job management, and a scalable bulk mailing system into a unified application, showcasing modern full-stack development with real-time features, secure authentication, and production-ready architecture.",
    techStack: [
      "React",
      "Tailwind CSS",
      "DaisyUI",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "Socket.IO",
      "Redis",
      "BullMQ",
      "Nodemailer",
      "Google OAuth",
      "Passport.js",
      "Cloudinary",
      "Multer",
      "Ollama",
      "LLaMA 3.1",
      "Google Calendar API",
      "FullCalendar",
      "Monaco Editor",
      "Axios",
      "JWT",
    ],
    coverImg: "/hero-image.jpg",
  },
  {
    title: "BulkMailer",
    completed: true,
    deployed: true,
    description:
      "BulkMailer is a scalable email automation platform designed to handle high-volume email campaigns efficiently. Built with a queue-based architecture using BullMQ and Redis, it offloads email processing to background workers while supporting Google OAuth, attachments, CC/BCC, and API-based integration for external applications, ensuring reliable and non-blocking email delivery.",
    techStack: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "Redis",
      "BullMQ",
      "Nodemailer",
      "Google OAuth",
      "Passport.js",
      "JWT",
      "Multer",
      "Axios",
      "REST API",
    ],
    coverImg: "/hero-image.jpg",
  },
];
